### ISSUE TITLE
Shouldn't the answer to question #6 be false?

### ISSUE THREAD

**Issue by BeejLuig** [learn-co-curriculum/javascript-css-quiz#3]
6. An element can only have one class at a time

True
False

If the question is not referring to the fact that you can have multiple classes attached to an HTML element, it may be worth rephrasing it. 

![screen shot 2017-03-03 at 7 42 07 pm](https://cloud.githubusercontent.com/assets/15836789/23574151/84b18bfc-0049-11e7-8778-db27753a9f5f.png)

From the [previous lesson](https://learn.co/tracks/full-stack-web-dev-with-react/advanced-javascript/html-and-css/introduction-to-css) 

![screen shot 2017-03-03 at 7 49 15 pm](https://cloud.githubusercontent.com/assets/15836789/23574241/881be5a2-004a-11e7-9ccd-5f3ac1d09df6.png)

**Comment by steveafrost** [comment]
+1

**Comment by mdo5004** [comment]
+1

**Comment by mdo5004** [comment]
I submitted a pull request to fix this issue

**Comment by kjleitz** [comment]
+1

**Comment by mdo5004** [comment]
@cernanb

**Comment by gj** [comment]
Fixed — thanks @BeejLuig !
